services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            # Ahora cualquier constructor que pida $owebHost recibirá este valor automáticamente
            $publicDir: '%app.public_dir%'
            $owebHost: '%app.host.oweb%'
            $panelHost: '%app.host.panel%'
            $googleTranslateCredentials: '%google_translate_auth%'
            $sunatApiToken: '%env(SUNAT_API_TOKEN)%'


    App\:
        resource: ../../src/
        exclude:
            - ../../src/DependencyInjection/
            - ../../src/Entity/
            - ../../src/Kernel.php
            - ../../src/pms/Service/Beds24/Sync/SyncContextScope.php
            - ../../src/Pms/
            - ../../src/Calendar/
            - ../../src/Exchange/

    Google\Cloud\Translate\V3\Client\TranslationServiceClient:
        arguments:
            $options:
                credentials: '%google_translate_auth%'




