services:
    _defaults:
        autowire: true
        autoconfigure: true
    app.admin.transporteservicio:
        class: App\Admin\TransporteServicioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteServicio
            controller: App\Controller\Admin\TransporteServicioController
            manager_type: orm
            group: Transporte
            label: Servicios de transporte
            show_mosaic_button: false
        calls:
            - [ setTokenStorage, [ "@security.token_storage" ] ]
            - [ setTemplate, [ list, admin/transporte_servicio/list.html.twig ] ]
            - [ setTemplate, [ edit, admin/transporte_servicio/edit.html.twig ] ]
        public: true
    app.admin.transporteserviciooperativo:
        class: App\Admin\TransporteServiciooperativoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteServiciooperativo
            manager_type: orm
            group: Transporte
            label: Información Operativa
            show_mosaic_button: false
        public: true
    app.admin.transporteserviciocontable:
        class: App\Admin\TransporteServiciocontableAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteServiciocontable
            controller: App\Controller\Admin\TransporteServiciocontableController
            manager_type: orm
            group: Transporte
            label: Contables
            show_mosaic_button: false
        calls:
            - [ setTemplate, [ edit, admin/transporte_serviciocontable/edit.html.twig ] ]
        public: true
    app.admin.transporteserviciocomponente:
        class: App\Admin\TransporteServiciocomponenteAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteServiciocomponente
            controller: App\Controller\Admin\TransporteServiciocomponenteController
            manager_type: orm
            group: Transporte
            label: Files de Transporte
            show_mosaic_button: false
        public: true
    app.admin.transporteconductor:
        class: App\Admin\TransporteConductorAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteConductor
            manager_type: orm
            group: Transporte
            label: Conductores
            show_mosaic_button: false
        public: true
    app.admin.transporteunidad:
        class: App\Admin\TransporteUnidadAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteUnidad
            manager_type: orm
            group: Transporte
            label: Unidades
            show_mosaic_button: false
        calls:
            - [ setTemplate, [ show, admin/transporte_unidad/show.html.twig ] ]
        public: true
    app.admin.transportetiposeroperativo:
        class: App\Admin\TransporteTiposeroperativoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteTiposeroperativo
            manager_type: orm
            group: Transporte
            label: Tipo operativo
            show_mosaic_button: false
        public: true
    app.admin.transportetipounibit:
        class: App\Admin\TransporteTipounibitAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteTipounibit
            manager_type: orm
            group: Transporte
            label: Tipo de bitácora
            show_mosaic_button: false
        public: true
    app.admin.transporteunidadbitacora:
        class: App\Admin\TransporteUnidadbitacoraAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\TransporteUnidadbitacora
            manager_type: orm
            group: Transporte
            label: Bitácoras
            show_mosaic_button: false
        public: true
