# config/services/services_message.yaml
services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\Message\:
        resource: '../../src/Message/'
        exclude:
            - '../../src/Message/Dto/'
            - '../../src/Messaage/Entity/'

    # =========================
    # controllers del m√≥dulo Pms
    # (fuera de src/Controller/)
    # =========================
    App\Message\Controller\:
        resource: '../../src/Message/Controller/'
        autowire: true
        autoconfigure: true
        tags:
            - 'controller.service_arguments'

