services:
    _defaults:
        autowire: true
        autoconfigure: true

    app.admin.cotizacionfile:
        class: App\Admin\CotizacionFileAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionFile
            controller: App\Controller\Admin\CotizacionFileController
            manager_type: orm
            group: Cotización
            label: Files de Cotización
            show_mosaic_button: false
        calls:
            - [ setTemplate, [ show, admin/cotizacion_file/show.html.twig ] ]
        public: true
    app.admin.cotizacionestadocotizacion:
        class: App\Admin\CotizacionEstadocotizacionAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionEstadocotizacion
            manager_type: orm
            group: Cotización
            label: Estado de cotización
            show_mosaic_button: false
        public: true
    app.admin.cotizacionestadocotcomponente:
        class: App\Admin\CotizacionEstadocotcomponenteAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionEstadocotcomponente
            manager_type: orm
            group: Cotización
            label: Estado de componente
            show_mosaic_button: false
        public: true
    app.admin.cotizacionfilepasajero:
        class: App\Admin\CotizacionFilepasajeroAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionFilepasajero
            manager_type: orm
            group: Cotización
            label: Name List
            show_mosaic_button: false
        public: true
    app.admin.cotizacioncottarifadetalle:
        class: App\Admin\CotizacionCottarifadetalleAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCottarifadetalle
            manager_type: orm
            group: Cotización
            label: Detalle de tarifa cotizada
            show_mosaic_button: false
        public: true
    app.admin.cotizaciontipofiledocumento:
        class: App\Admin\CotizacionTipofiledocumentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionTipofiledocumento
            manager_type: orm
            group: Cotización
            label: Tipo de archivo adjunto
            show_mosaic_button: false
        public: true
    app.admin.cotizacionfiledocumento:
        class: App\Admin\CotizacionFiledocumentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionFiledocumento
            manager_type: orm
            group: Cotización
            label: Archivos adjuntos
            show_mosaic_button: false
        public: true
    app.admin.cotizacionmenu:
        class: App\Admin\CotizacionMenuAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionMenu
            manager_type: orm
            group: Cotización
            label: Menús de Cotización
            show_mosaic_button: false
        public: true
    app.admin.cotizacionmenulink:
        class: App\Admin\CotizacionMenulinkAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionMenulink
            manager_type: orm
            group: Cotización
            label: Vínculos Menú ↔ Cotización
            show_mosaic_button: false
    app.admin.cotizacioncotpolitica:
        class: App\Admin\CotizacionCotpoliticaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCotpolitica
            controller: App\Controller\Admin\CotizacionCotpoliticaController
            manager_type: orm
            group: Cotización
            label: Políticas
            show_mosaic_button: false
        public: true
    app.admin.cotizacioncotnota:
        class: App\Admin\CotizacionCotnotaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCotnota
            controller: App\Controller\Admin\CotizacionCotnotaController
            manager_type: orm
            group: Cotización
            label: Notas operativas
            show_mosaic_button: false
        public: true
    app.admin.cotizacioncotizacion:
        class: App\Admin\CotizacionCotizacionAdmin
        arguments:
        - '@security.token_storage'
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCotizacion
            controller: App\Controller\Admin\CotizacionCotizacionController
            manager_type: orm
            group: Cotizacion
            label: Cotizaciones
        calls:
            - [ setTemplate, [ show, admin/cotizacion_cotizacion/show.html.twig ] ]
            - [ setTemplate, [ edit, admin/cotizacion_cotizacion/edit.html.twig ] ]
            - [ setTemplate, [ list, admin/cotizacion_cotizacion/list.html.twig ] ]
        public: true
    app.admin.cotizacioncotservicio:
        class: App\Admin\CotizacionCotservicioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCotservicio
            controller: App\Controller\Admin\CotizacionCotservicioController
            manager_type: orm
            group: Cotizacion
            label: Servicios cotizados
        calls:
            - [ setTemplate, [ edit, admin/cotizacion_cotservicio/edit.html.twig ] ]
            - [ setTemplate, [ list, admin/cotizacion_cotservicio/list.html.twig ] ]
            - [ setTemplate, [ show, admin/cotizacion_cotservicio/show.html.twig ] ]
        public: true
    app.admin.cotizacioncotcomponente:
        class: App\Admin\CotizacionCotcomponenteAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCotcomponente
            controller: App\Controller\Admin\CotizacionCotcomponenteController
            manager_type: orm
            group: Cotizacion
            label: Componentes
        calls:
            - [ setTemplate, [ list, admin/cotizacion_cotcomponente/list.html.twig ] ]
            - [ setTemplate, [ show, admin/cotizacion_cotcomponente/show.html.twig ] ]
        public: true
    app.admin.cotizacioncotcomponenteoperativa:
        class: App\Admin\CotizacionCotcomponenteoperativaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCotcomponenteoperativa
            manager_type: orm
            group: Cotizacion
            label: Comp. Operativa
        public: true
    app.admin.viewcotizacioncotcomponentealerta:
        class: App\Admin\ViewCotizacionCotcomponenteAlertaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ViewCotizacionCotcomponenteAlerta
            manager_type: orm
            group: Cotizacion
            label: Alertas
        public: true
    app.admin.cotizacioncottarifa:
        class: App\Admin\CotizacionCottarifaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CotizacionCottarifa
            manager_type: orm
            group: Cotizacion
            label: Tarifa cotizada
            show_mosaic_button: false
        public: true
