services:
    _defaults:
        autowire: true
        autoconfigure: true
    app.admin.servicioservicio:
        class: App\Admin\ServicioServicioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioServicio
            controller: App\Controller\Admin\ServicioServicioController
            manager_type: orm
            group: Servicio
            label: Servicio para cotizar
            show_mosaic_button: false
        public: true
    app.admin.servicioitinerario:
        class: App\Admin\ServicioItinerarioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioItinerario
            controller: App\Controller\Admin\ServicioItinerarioController
            manager_type: orm
            group: Servicio
            label: Itinerario
            show_mosaic_button: false
        public: true
    app.admin.serviciocomponente:
        class: App\Admin\ServicioComponenteAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioComponente
            controller: App\Controller\Admin\ServicioComponenteController
            manager_type: orm
            group: Servicio
            label: Componente
            show_mosaic_button: false
        public: true
    app.admin.serviciocomponenteitem:
        class: App\Admin\ServicioComponenteitemAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioComponenteitem
            controller: App\Controller\Admin\ServicioComponenteitemController
            manager_type: orm
            group: Servicio
            label: Item de Componente
            show_mosaic_button: false
        public: true
    app.admin.serviciotipocomponente:
        class: App\Admin\ServicioTipocomponenteAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioTipocomponente
            manager_type: orm
            group: Servicio
            label: Tipo de componente
            show_mosaic_button: false
        public: true
    app.admin.serviciotarifa:
        class: App\Admin\ServicioTarifaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioTarifa
            controller: App\Controller\Admin\ServicioTarifaController
            manager_type: orm
            group: Servicio
            label: Tarifa para cotizar
            show_mosaic_button: false
        public: true
    app.admin.servicioprovider:
        class: App\Admin\ServicioProviderAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioProvider
            manager_type: orm
            group: Servicio
            label: Proveedor
            show_mosaic_button: false
        public: true
    app.admin.servicioprovidermedio:
        class: App\Admin\ServicioProvidermedioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioProvidermedio
            controller: App\Controller\Admin\ServicioProvidermedioController
            manager_type: orm
            group: Servicio
            label: Proveedor Multimedia
            show_mosaic_button: false
        public: true
    app.admin.servicioitinerariodia:
        class: App\Admin\ServicioItinerariodiaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioItinerariodia
            controller: App\Controller\Admin\ServicioItinerariodiaController
            manager_type: orm
            group: Servicio
            label: Dias de itinerario
            show_mosaic_button: false
        public: true
    app.admin.servicionotaitinerariodia:
        class: App\Admin\ServicioNotaitinerariodiaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioNotaitinerariodia
            controller: App\Controller\Admin\ServicioNotaitinerariodiaController
            manager_type: orm
            group: Servicio
            label: Notas de itinerarios
            show_mosaic_button: false
        public: true
    app.admin.servicioitidiaarchivo:
        class: App\Admin\ServicioItidiaarchivoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioItidiaarchivo
            manager_type: orm
            group: Servicio
            label: Archivo del itinerario
            show_mosaic_button: false
        public: true
    app.admin.serviciotipotarifa:
        class: App\Admin\ServicioTipotarifaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioTipotarifa
            manager_type: orm
            group: Servicio
            label: Tipo de tarifa
            show_mosaic_button: false
        public: true
    app.admin.serviciomodalidadtarifa:
        class: App\Admin\ServicioModalidadtarifaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioModalidadtarifa
            manager_type: orm
            group: Servicio
            label: Modalidad de tarifa
            show_mosaic_button: false
        public: true
    app.admin.serviciotipotarifadetalle:
        class: App\Admin\ServicioTipotarifadetalleAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\ServicioTipotarifadetalle
            manager_type: orm
            group: Servicio Maestro
            label: Tipo de detalle de tarifa
            show_mosaic_button: false
        public: true
