services:
    _defaults:
        autowire: true
        autoconfigure: true
    app.admin.fitdieta:
        class: App\Admin\FitDietaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitDieta
            controller: App\Controller\Admin\FitDietaController
            manager_type: orm
            group: Fit
            label: Dieta
            show_mosaic_button: false
        calls:
            - [ setTemplate, [ edit, admin/fit_dieta/edit.html.twig ] ]
            - [ setTemplate, [ list, admin/fit_dieta/list.html.twig ] ]
            - [ setTemplate, [ show, admin/fit_dieta/show.html.twig ] ]
        public: true
    app.admin.fitdietacomida:
        class: App\Admin\FitDietacomidaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitDietacomida
            manager_type: orm
            group: Fit
            label: Comidas
            show_mosaic_button: false
        public: true
    app.admin.fitdietaalimento:
        class: App\Admin\FitDietaalimentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitDietaalimento
            manager_type: orm
            group: Fit
            label: Alimentos de la dieta
            show_mosaic_button: false
        public: true
    app.admin.fittipodieta:
        class: App\Admin\FitTipodietaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitTipodieta
            manager_type: orm
            group: Fit
            label: Tipo de dietas
            show_mosaic_button: false
        public: true
    app.admin.fitalimento:
        class: App\Admin\FitAlimentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitAlimento
            manager_type: orm
            group: Fit
            label: Lista de alimentos
            show_mosaic_button: false
        public: true
    app.admin.fittipoalimento:
        class: App\Admin\FitTipoalimentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitTipoalimento
            manager_type: orm
            group: Fit
            label: Tipo de alimento
            show_mosaic_button: false
        public: true
    app.admin.fitmedidaalimento:
        class: App\Admin\FitMedidaalimentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\FitMedidaalimento
            manager_type: orm
            group: Fit
            label: Medida de alimento
            show_mosaic_button: false
        public: true
