services:
    _defaults:
        autowire: true
        autoconfigure: true
    app.admin.cuentacuenta:
        class: App\Admin\CuentaCuentaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CuentaCuenta
            manager_type: orm
            group: Cuentas y cajas
            label: Cuenta
            show_mosaic_button: false
        public: true
    app.admin.cuentamovimiento:
        class: App\Admin\CuentaMovimientoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CuentaMovimiento
            manager_type: orm
            group: Cuenta
            label: Movimiento
            show_mosaic_button: false
        calls:
            - [ setTemplate, [ list, admin/cuenta_movimiento/list.html.twig ] ]
        public: true
    app.admin.cuentaclase:
        class: App\Admin\CuentaClaseAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CuentaClase
            manager_type: orm
            group: Cuenta
            label: Clase de movimiento
            show_mosaic_button: false
        public: true
    app.admin.cuentacentro:
        class: App\Admin\CuentaCentroAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CuentaCentro
            manager_type: orm
            group: Cuenta
            label: Centro de costo
            show_mosaic_button: false
        public: true
    app.admin.cuentaperiodo:
        class: App\Admin\CuentaPeriodoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CuentaPeriodo
            manager_type: orm
            group: Cuenta
            label: Periodo
            show_mosaic_button: false
        calls:
            - [ setTemplate, [ edit, admin/cuenta_periodo/edit.html.twig ] ]
        public: true
    app.admin.cuentatipo:
        class: App\Admin\CuentaTipoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\CuentaTipo
            manager_type: orm
            group: Cuenta
            label: Tipo de movimiento
            show_mosaic_button: false
        public: true
