services:
    _defaults:
        autowire: true
        autoconfigure: true
    app.admin.maestrosexo:
        class: App\Admin\MaestroSexoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroSexo
            manager_type: orm
            group: Maestros
            label: Sexo
            show_mosaic_button: false
        public: true
    app.admin.maestrotipodocumento:
        class: App\Admin\MaestroTipodocumentoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroTipodocumento
            manager_type: orm
            group: Maestros
            label: Tipo de documento de identidad
            show_mosaic_button: false
        public: true
    app.admin.maestromoneda:
        class: App\Admin\MaestroMonedaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroMoneda
            manager_type: orm
            group: Maestros
            label: Monedas
            show_mosaic_button: false
        public: true
    app.admin.maestrotipocambio:
        class: App\Admin\MaestroTipocambioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroTipocambio
            manager_type: orm
            group: Maestros
            label: Tipo de cambio
            show_mosaic_button: false
        public: true
    app.admin.maestrocontacto:
        class: App\Admin\MaestroContactoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroContacto
            manager_type: orm
            group: Maestros
            label: Contacto
            show_mosaic_button: false
        public: true
    app.admin.maestrotipocontacto:
        class: App\Admin\MaestroTipocontactoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroTipocontacto
            manager_type: orm
            group: Maestros
            label: Tipo de contacto
            show_mosaic_button: false
        public: true
    app.admin.maestropais:
        class: App\Admin\MaestroPaisAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroPais
            manager_type: orm
            group: Maestros
            label: Pais
            show_mosaic_button: false
        public: true
    app.admin.maestroidioma:
        class: App\Admin\MaestroIdiomaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroIdioma
            manager_type: orm
            group: Maestros
            label: Idioma
            show_mosaic_button: false
        public: true
    app.admin.maestrotipopax:
        class: App\Admin\MaestroTipopaxAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroTipopax
            manager_type: orm
            group: Maestros
            label: Tipo de pasajero
            show_mosaic_button: false
        public: true
    app.admin.maestrocategoriatour:
        class: App\Admin\MaestroCategoriatourAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroCategoriatour
            manager_type: orm
            group: Maestros
            label: Categoria de tour
            show_mosaic_button: false
        public: true
    app.admin.maestromedio:
        class: App\Admin\MaestroMedioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroMedio
            controller: App\Controller\Admin\MaestroMedioController
            manager_type: orm
            group: Maestros
            label: Multimedia
            show_mosaic_button: false
        public: true
    app.admin.maestroclasemedio:
        class: App\Admin\MaestroClasemedioAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\MaestroClasemedio
            manager_type: orm
            group: Maestros
            label: Clase Multimedia
            show_mosaic_button: false
        public: true
