services:
    _defaults:
        autowire: true
        autoconfigure: true
    app.admin.userorganizacion:
        class: App\Admin\UserOrganizacionAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\UserOrganizacion
            manager_type: orm
            group: Organización
            label: Organizaciones
            show_mosaic_button: false
        public: true
    app.admin.userdependencia:
        class: App\Admin\UserDependenciaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\UserDependencia
            manager_type: orm
            group: Organización
            label: Dependencias
            show_mosaic_button: false
        public: true
    app.admin.userarea:
        class: App\Admin\UserAreaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\UserArea
            manager_type: orm
            group: Organización
            label: Areas
            show_mosaic_button: false
        public: true
    app.admin.usercuenta:
        class: App\Admin\UserCuentaAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\UserCuenta
            manager_type: orm
            group: Organización
            label: Cuentas de usuario
            show_mosaic_button: false
        public: true
    app.admin.usercuentatipo:
        class: App\Admin\UserCuentatipoAdmin
        tags:
        -   name: sonata.admin
            model_class: App\Entity\UserCuentatipo
            manager_type: orm
            group: Organización
            label: Tipos de cuentas
            show_mosaic_button: false
        public: true
