services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: ../../src/
        exclude:
            - ../../src/DependencyInjection/
            - ../../src/Entity/
            - ../../src/Kernel.php
            - ../../src/pms/Service/Beds24/Sync/SyncContextScope.php

    app.doctrine.entity_path_initializer:
        class: App\EventSubscriber\EntityPathInitializerSubscriber
        arguments:
            $publicDir: '%app.public_dir%'
        tags:
        -   name: doctrine.event_subscriber
    app.service.admin_decorating_data_source:
        class: App\Service\AdminDecoratingDataSource
        decorates: sonata.admin.data_source.orm

    app.event_Listener_controller_request_kernel_event_listener:
        class: App\EventListener\ControllerRequestKernelEventListener
        tags:
        -   name: kernel.event_listener
            event: kernel.controller
            method: onControllerRequest
    app.event_Listener_kernel_request_kernel_event_listener:
        class: App\EventListener\KernelRequestKernelEventListener
        tags:
        -   name: kernel.event_listener
            event: kernel.request
            method: onKernelRequest
            priority: 101
    app.block.tareas_block_service:
        class: App\Block\TareasBlockService
        tags:
        -   name: sonata.block

    Gedmo\Translatable\TranslatableListener:
        alias: 'stof_doctrine_extensions.listener.translatable'