admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /
    host: '%app.host.oweb%'

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /
    host: '%app.host.oweb%'
