#controllers:
#    resource: ../src/Controller/
#    type: annotation

# FRONT (web / CMS)
front_controllers:
    resource: ../src/Controller/Front/
    type: attribute
    host: '%app.host.front%'

# API (ajax, ical, calendar, etc.)
api_controllers:
    resource: ../src/Controller/Api/
    type: attribute
    host: '%app.host.api%'

# Calendar (módulo nuevo)
calendar_controllers:
    resource: ../src/Calendar/Controller/
    type: attribute
    host: '%app.host.api%'

# webhook (módulo nuevo)
webhook_controllers:
    resource: ../src/Pms/Controller/Webhook/
    type: attribute
    host: '%app.host.api%'

# Panel (Easyadmin)
panel_controllers:
    resource: ../src/Controller/Panel/
    type: attribute
    host: '%app.host.panel%'

# Admin (Sonata / legacy controlado)
admin_controllers:
    resource: ../src/Controller/Admin/
    type: annotation
    host: '%app.host.oweb%'

kernel:
    resource: ../src/Kernel.php
    type: attribute

sonata_translation:
    resource: '@SonataTranslationBundle/Resources/config/routes.yaml'
    host: '%app.host.oweb%'

