#controllers:
#    resource: ../src/Controller/
#    type: annotation

security_global:
    resource: ../src/Controller/SecurityController.php
    type: attribute

# FRONT (web / CMS)
front_controllers:
    resource: ../src/Front/Controller/
    type: attribute
    host: '%app.host.front%'

# API (ajax, ical, calendar, etc.)
api_controllers:
    resource: ../src/Api/Controller/
    type: attribute
    host: '%app.host.api%'

# Calendar (módulo nuevo)
calendar_controllers:
    resource: ../src/Calendar/Controller/
    type: attribute
    host: '%app.host.api%'

# webhook (módulo nuevo)
webhook_controllers:
    resource: ../src/Pms/Controller/Webhook/
    type: attribute
    host: '%app.host.api%'

# Panel (Easyadmin)
panel_controllers:
    resource: ../src/Panel/Controller/
    type: attribute
    host: '%app.host.panel%'

# Admin (Oweb / legacy controlado)
oweb_controllers:
    resource: ../src/Oweb/Controller/
    type: attribute
    host: '%app.host.oweb%'

kernel:
    resource: ../src/Kernel.php
    type: attribute

sonata_translation:
    resource: '@SonataTranslationBundle/Resources/config/routes.yaml'
    host: '%app.host.oweb%'

